import React, { useRef, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Printer, 
  Download, 
  Mail, 
  MessageCircle, 
  Share2, 
  Copy,
  Loader2,
  CheckCircle,
  FileText
} from "lucide-react";
import { toast } from "sonner";
import { base44 } from "@/api/base44Client";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const formatCurrency = (amount, currency = "CAD") => {
  const symbols = { CAD: "CA$", USD: "$", NGN: "₦" };
  return `${symbols[currency] || "$"}${(amount || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-CA');
};

const formatPhone = (phone) => {
  if (!phone) return '';
  const cleaned = phone.replace(/\D/g, '');
  if (cleaned.length === 10) {
    return `${cleaned.slice(0, 3)}-${cleaned.slice(3, 6)}-${cleaned.slice(6)}`;
  }
  if (cleaned.length === 11 && cleaned.startsWith('1')) {
    return `${cleaned.slice(1, 4)}-${cleaned.slice(4, 7)}-${cleaned.slice(7)}`;
  }
  return phone;
};

export default function DocumentViewer({ 
  open, 
  onClose, 
  documentType = "invoice", // invoice, quote, bill_of_sale, statement, repair_invoice, freight_invoice
  documentData,
  company,
  customer,
  title
}) {
  const documentRef = useRef(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(null);

  if (!documentData) return null;

  const docTitles = {
    invoice: "INVOICE",
    quote: "QUOTATION",
    bill_of_sale: "BILL OF SALE",
    statement: "ACCOUNT STATEMENT",
    repair_invoice: "REPAIR INVOICE",
    freight_invoice: "FREIGHT INVOICE",
    purchase_order: "PURCHASE ORDER"
  };

  const docTitle = title || docTitles[documentType] || "DOCUMENT";
  const currency = documentData.currency || "CAD";

  const generatePlainText = () => {
    const lines = [
      `${docTitle}`,
      `${company?.name || 'Company'}`,
      `================================`,
      ``,
      `Document #: ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}`,
      `Date: ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}`,
      documentData.due_date ? `Due Date: ${formatDate(documentData.due_date)}` : '',
      ``,
      `Customer: ${documentData.customer_name || customer?.full_name || 'N/A'}`,
      documentData.customer_email ? `Email: ${documentData.customer_email}` : '',
      documentData.customer_phone ? `Phone: ${documentData.customer_phone}` : '',
      documentData.customer_address ? `Address: ${documentData.customer_address}` : '',
      ``
    ].filter(Boolean);

    if (documentData.vehicle_details || documentData.vehicle_vin) {
      lines.push(`VEHICLE INFORMATION`);
      lines.push(`-------------------`);
      if (documentData.vehicle_details) lines.push(documentData.vehicle_details);
      if (documentData.vehicle_vin) lines.push(`VIN: ${documentData.vehicle_vin}`);
      if (documentData.vehicle_mileage) lines.push(`Mileage: ${documentData.vehicle_mileage} km`);
      lines.push(``);
    }

    lines.push(`LINE ITEMS`);
    lines.push(`----------`);
    (documentData.line_items || []).forEach(item => {
      lines.push(`${item.description}: ${item.quantity} x ${formatCurrency(item.unit_price || item.rate, currency)} = ${formatCurrency(item.total || item.amount, currency)}`);
    });

    lines.push(``);
    lines.push(`TOTALS`);
    lines.push(`------`);
    lines.push(`Subtotal: ${formatCurrency(documentData.subtotal, currency)}`);
    if (documentData.tax_amount) lines.push(`Tax: ${formatCurrency(documentData.tax_amount, currency)}`);
    lines.push(`Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`);
    if (documentData.amount_paid) lines.push(`Paid: ${formatCurrency(documentData.amount_paid, currency)}`);
    if (documentData.balance_due) lines.push(`Balance Due: ${formatCurrency(documentData.balance_due, currency)}`);

    lines.push(``);
    lines.push(`---`);
    lines.push(`Generated by eFinAuto OFMS • ${new Date().toLocaleString()}`);

    return lines.join('\n');
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(generatePrintHTML());
    printWindow.document.close();
    printWindow.print();
  };

  const generatePrintHTML = () => {
    const lineItemsHTML = (documentData.line_items || []).map(item => `
      <tr>
        <td>${item.description || ''}</td>
        <td class="right">${item.quantity || 1}</td>
        <td class="right">${formatCurrency(item.unit_price || item.rate || 0, currency)}</td>
        <td class="right">${formatCurrency(item.total || item.amount || ((item.quantity || 1) * (item.unit_price || item.rate || 0)), currency)}</td>
      </tr>
    `).join('');

    // Calculate tax properly
    const subtotal = documentData.subtotal || (documentData.line_items || []).reduce((sum, item) => sum + (item.total || item.amount || ((item.quantity || 1) * (item.unit_price || item.rate || 0))), 0);
    const taxRate = documentData.tax_rate || 0;
    const taxAmount = documentData.tax_amount || (subtotal * taxRate / 100);
    const totalAmount = documentData.total_amount || documentData.grand_total || (subtotal + taxAmount);

    return `
      <html>
        <head>
          <title>${docTitle} - ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: 'Segoe UI', Arial, sans-serif; padding: 0; margin: 0; color: #333; font-size: 10pt; line-height: 1.4; }
            .invoice-container { max-width: 800px; margin: 0 auto; background: #fff; }
            .header { background: #1a5f7a; color: white; padding: 25px 30px; display: flex; justify-content: space-between; align-items: flex-start; }
            .company-info { }
            .company-name { font-size: 20pt; font-weight: 600; margin-bottom: 8px; }
            .company-details { font-size: 9pt; opacity: 0.9; line-height: 1.6; }
            .invoice-title { text-align: right; }
            .invoice-title h1 { font-size: 28pt; font-weight: 300; letter-spacing: 2px; margin-bottom: 5px; }
            .invoice-number { font-size: 11pt; opacity: 0.9; }
            .content { padding: 30px; }
            .info-section { display: flex; justify-content: space-between; margin-bottom: 30px; }
            .bill-to { flex: 1; }
            .bill-to-label { font-size: 9pt; color: #666; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; font-weight: 600; }
            .bill-to-name { font-size: 12pt; font-weight: 600; color: #1a5f7a; margin-bottom: 5px; }
            .bill-to-details { font-size: 10pt; color: #555; line-height: 1.6; }
            .invoice-details { text-align: right; }
            .invoice-details-table { margin-left: auto; }
            .invoice-details-table td { padding: 4px 0; font-size: 10pt; }
            .invoice-details-table td:first-child { color: #666; padding-right: 15px; }
            .invoice-details-table td:last-child { font-weight: 500; color: #333; }
            .items-table { width: 100%; border-collapse: collapse; margin-bottom: 25px; }
            .items-table th { background: #f8f9fa; padding: 12px 15px; text-align: left; font-size: 9pt; font-weight: 600; color: #555; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #1a5f7a; }
            .items-table th.right { text-align: right; }
            .items-table td { padding: 15px; border-bottom: 1px solid #eee; font-size: 10pt; }
            .items-table td.right { text-align: right; }
            .items-table tr:hover { background: #fafafa; }
            .totals-wrapper { display: flex; justify-content: flex-end; }
            .totals-table { width: 280px; }
            .totals-table td { padding: 8px 0; font-size: 10pt; }
            .totals-table td:first-child { color: #666; }
            .totals-table td:last-child { text-align: right; font-weight: 500; }
            .totals-table .subtotal-row td { border-top: 1px solid #eee; padding-top: 15px; }
            .totals-table .total-row td { border-top: 2px solid #1a5f7a; padding-top: 12px; font-size: 14pt; font-weight: 700; }
            .totals-table .total-row td:last-child { color: #1a5f7a; }
            .totals-table .balance-row td { background: #fff3cd; padding: 10px 8px; font-weight: 600; }
            .totals-table .balance-row td:last-child { color: #856404; }
            .footer-section { margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; }
            .thank-you { font-size: 12pt; color: #1a5f7a; font-weight: 500; margin-bottom: 15px; }
            .tax-numbers { display: flex; gap: 25px; font-size: 9pt; color: #666; }
            .tax-numbers span { }
            .notes-section { margin-top: 20px; padding: 15px; background: #f8f9fa; border-radius: 4px; border-left: 3px solid #1a5f7a; }
            .notes-section h4 { font-size: 9pt; color: #666; text-transform: uppercase; margin-bottom: 8px; }
            .notes-section p { font-size: 10pt; color: #555; }
            .vehicle-box { background: #e8f4f8; padding: 15px; border-radius: 4px; margin-bottom: 20px; border-left: 3px solid #1a5f7a; }
            .vehicle-box h4 { font-size: 9pt; color: #1a5f7a; text-transform: uppercase; margin-bottom: 8px; font-weight: 600; }
            .vehicle-box p { font-size: 10pt; color: #333; margin: 3px 0; }
            .signature-area { margin-top: 40px; display: grid; grid-template-columns: 1fr 1fr; gap: 60px; }
            .signature-line { border-top: 1px solid #333; padding-top: 8px; text-align: center; font-size: 9pt; color: #666; }
            .powered-by { text-align: center; margin-top: 30px; font-size: 8pt; color: #999; }
            @media print { 
              body { padding: 0; } 
              .header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
              .items-table th { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            }
          </style>
        </head>
        <body>
          <div class="invoice-container">
            <div class="header">
              <div class="company-info">
                <div class="company-name">${company?.name || 'Company Name'}</div>
                <div class="company-details">
                  ${company?.address ? `${company.address}<br>` : ''}
                  ${company?.city ? `${company.city}, ${company?.province || ''} ${company?.postal_code || ''}<br>` : ''}
                  ${company?.phone ? `Tel: ${formatPhone(company.phone)}<br>` : ''}
                  ${company?.email ? `${company.email}` : ''}
                </div>
              </div>
              <div class="invoice-title">
                <h1>${docTitle}</h1>
                <div class="invoice-number">#${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}</div>
              </div>
            </div>

            <div class="content">
              <div class="info-section">
                <div class="bill-to">
                  <div class="bill-to-label">Bill To</div>
                  <div class="bill-to-name">${documentData.customer_name || customer?.full_name || 'Customer'}</div>
                  <div class="bill-to-details">
                    ${documentData.customer_email ? `${documentData.customer_email}<br>` : ''}
                    ${documentData.customer_phone ? `${formatPhone(documentData.customer_phone)}<br>` : ''}
                    ${documentData.customer_address ? `${documentData.customer_address}` : ''}
                  </div>
                </div>
                <div class="invoice-details">
                  <table class="invoice-details-table">
                    <tr><td>Invoice Date:</td><td>${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}</td></tr>
                    ${documentData.due_date ? `<tr><td>Due Date:</td><td>${formatDate(documentData.due_date)}</td></tr>` : ''}
                    ${documentData.currency ? `<tr><td>Currency:</td><td>${documentData.currency}</td></tr>` : ''}
                    ${documentData.payment_terms ? `<tr><td>Terms:</td><td>${documentData.payment_terms}</td></tr>` : ''}
                  </table>
                </div>
              </div>

              ${(documentData.vehicle_details || documentData.vehicle_vin) ? `
              <div class="vehicle-box">
                <h4>Vehicle Information</h4>
                ${documentData.vehicle_details ? `<p><strong>${documentData.vehicle_details}</strong></p>` : ''}
                ${documentData.vehicle_vin ? `<p>VIN: ${documentData.vehicle_vin}</p>` : ''}
                ${documentData.vehicle_mileage ? `<p>Mileage: ${documentData.vehicle_mileage?.toLocaleString()} km</p>` : ''}
                ${documentData.vehicle_color ? `<p>Color: ${documentData.vehicle_color}</p>` : ''}
              </div>
              ` : ''}

              <table class="items-table">
                <thead>
                  <tr>
                    <th style="width: 50%;">Item & Description</th>
                    <th class="right" style="width: 15%;">Qty</th>
                    <th class="right" style="width: 17%;">Rate</th>
                    <th class="right" style="width: 18%;">Amount</th>
                  </tr>
                </thead>
                <tbody>
                  ${lineItemsHTML || '<tr><td colspan="4" style="text-align: center; padding: 30px; color: #999;">No items</td></tr>'}
                </tbody>
              </table>

              <div class="totals-wrapper">
                <table class="totals-table">
                  <tr class="subtotal-row"><td>Subtotal</td><td>${formatCurrency(subtotal, currency)}</td></tr>
                  <tr><td>Tax (${taxRate}%)</td><td>${formatCurrency(taxAmount, currency)}</td></tr>
                  ${documentData.discount ? `<tr><td>Discount</td><td>-${formatCurrency(documentData.discount, currency)}</td></tr>` : ''}
                  <tr class="total-row"><td>Total</td><td>${formatCurrency(totalAmount, currency)}</td></tr>
                  ${documentData.amount_paid > 0 ? `<tr><td>Payment Made</td><td>(-) ${formatCurrency(documentData.amount_paid, currency)}</td></tr>` : ''}
                  ${documentData.balance_due > 0 ? `<tr class="balance-row"><td>Balance Due</td><td>${formatCurrency(documentData.balance_due, currency)}</td></tr>` : ''}
                </table>
              </div>

              <div class="footer-section">
                <div class="thank-you">Thank you for your business!</div>
                <div class="tax-numbers">
                  ${company?.gst_number ? `<span><strong>GST #:</strong> ${company.gst_number}</span>` : ''}
                  ${company?.pst_number ? `<span><strong>PST #:</strong> ${company.pst_number}</span>` : ''}
                  ${company?.dealer_permit_number ? `<span><strong>Dealer Permit #:</strong> ${company.dealer_permit_number}</span>` : ''}
                </div>
              </div>

              ${documentData.notes ? `
              <div class="notes-section">
                <h4>Notes</h4>
                <p>${documentData.notes}</p>
              </div>
              ` : ''}

              ${documentType === 'bill_of_sale' ? `
              <div class="signature-area">
                <div>
                  <div class="signature-line">Seller Signature</div>
                </div>
                <div>
                  <div class="signature-line">Buyer Signature</div>
                </div>
              </div>
              ` : ''}

              <div class="powered-by">Generated by eFinAuto OFMS</div>
            </div>
          </div>
        </body>
      </html>
    `;
  };

  const handleDownloadPDF = async () => {
    if (!documentRef.current) return;

    try {
      toast.loading("Generating PDF...");
      const canvas = await html2canvas(documentRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "letter");
      const imgWidth = 216;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      let heightLeft = imgHeight;
      let position = 0;
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= 279;
      
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= 279;
      }
      
      const filename = `${docTitle.replace(/\s/g, '_')}-${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'doc'}.pdf`;
      pdf.save(filename);
      
      toast.dismiss();
      toast.success("PDF downloaded");
      setShareSuccess('pdf');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.dismiss();
      toast.error("Failed to generate PDF");
    }
  };

  const handleEmailShare = async () => {
    const emailTo = documentData.customer_email || customer?.email || prompt("Enter recipient email:");
    if (!emailTo) return;

    setSendingEmail(true);
    try {
      await base44.integrations.Core.SendEmail({
        to: emailTo,
        subject: `${docTitle} ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''} from ${company?.name || 'Our Company'}`,
        body: generatePlainText()
      });
      toast.success(`Sent to ${emailTo}`);
      setShareSuccess('email');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.error("Failed to send email");
    } finally {
      setSendingEmail(false);
    }
  };

  const handleWhatsAppShare = () => {
    const message = `*${docTitle}*
${company?.name || 'Company'}

*#:* ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
*Customer:* ${documentData.customer_name || 'N/A'}
*Date:* ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date)}

*Total:* ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}
${documentData.balance_due > 0 ? `*Balance Due:* ${formatCurrency(documentData.balance_due, currency)}` : ''}

_Generated by eFinAuto OFMS_`;

    const phone = documentData.customer_phone?.replace(/\D/g, '') || '';
    window.open(phone ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : `https://wa.me/?text=${encodeURIComponent(message)}`, "_blank");
    setShareSuccess('whatsapp');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  const handleGoogleChatShare = () => {
    const message = `📄 ${docTitle} #${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
Customer: ${documentData.customer_name || 'N/A'}
Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`;
    navigator.clipboard.writeText(message);
    toast.success("Copied for Google Chat");
    setShareSuccess('gchat');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            {docTitle}
          </DialogTitle>
        </DialogHeader>

        {/* Share Actions */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h3 className="font-semibold flex items-center gap-2 text-sm">
                <Share2 className="w-4 h-4" />
                Print & Share
              </h3>
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="w-4 h-4 mr-2" />
                  Print
                </Button>
                <Button variant="outline" size="sm" onClick={handleDownloadPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  PDF
                  {shareSuccess === 'pdf' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" onClick={handleEmailShare} disabled={sendingEmail}>
                  {sendingEmail ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
                  Email
                  {shareSuccess === 'email' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" className="bg-green-50 text-green-700" onClick={handleWhatsAppShare}>
                  <MessageCircle className="w-4 h-4 mr-2" />
                  WhatsApp
                </Button>
                <Button variant="outline" size="sm" className="bg-blue-50 text-blue-700" onClick={handleGoogleChatShare}>
                  <Copy className="w-4 h-4 mr-2" />
                  Google Chat
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Document Preview */}
        <div ref={documentRef} className="bg-white p-6 border rounded-lg" dangerouslySetInnerHTML={{ __html: generatePrintHTML().replace(/<\/?html>|<\/?head>|<\/?body>|<title>.*?<\/title>|<style>[\s\S]*?<\/style>/gi, '') }} />
      </DialogContent>
    </Dialog>
  );
}