import React, { useRef, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Printer, 
  Download, 
  Mail, 
  MessageCircle, 
  Share2, 
  Copy,
  Loader2,
  CheckCircle,
  FileText
} from "lucide-react";
import { toast } from "sonner";
import { base44 } from "@/api/base44Client";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const formatCurrency = (amount, currency = "CAD") => {
  const symbols = { CAD: "CA$", USD: "$", NGN: "₦" };
  return `${symbols[currency] || "$"}${(amount || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-CA');
};

export default function DocumentViewer({ 
  open, 
  onClose, 
  documentType = "invoice", // invoice, quote, bill_of_sale, statement, repair_invoice, freight_invoice
  documentData,
  company,
  customer,
  title
}) {
  const documentRef = useRef(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(null);

  if (!documentData) return null;

  const docTitles = {
    invoice: "INVOICE",
    quote: "QUOTATION",
    bill_of_sale: "BILL OF SALE",
    statement: "ACCOUNT STATEMENT",
    repair_invoice: "REPAIR INVOICE",
    freight_invoice: "FREIGHT INVOICE",
    purchase_order: "PURCHASE ORDER"
  };

  const docTitle = title || docTitles[documentType] || "DOCUMENT";
  const currency = documentData.currency || "CAD";

  const generatePlainText = () => {
    const lines = [
      `${docTitle}`,
      `${company?.name || 'Company'}`,
      `================================`,
      ``,
      `Document #: ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}`,
      `Date: ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}`,
      documentData.due_date ? `Due Date: ${formatDate(documentData.due_date)}` : '',
      ``,
      `Customer: ${documentData.customer_name || customer?.full_name || 'N/A'}`,
      documentData.customer_email ? `Email: ${documentData.customer_email}` : '',
      documentData.customer_phone ? `Phone: ${documentData.customer_phone}` : '',
      documentData.customer_address ? `Address: ${documentData.customer_address}` : '',
      ``
    ].filter(Boolean);

    if (documentData.vehicle_details || documentData.vehicle_vin) {
      lines.push(`VEHICLE INFORMATION`);
      lines.push(`-------------------`);
      if (documentData.vehicle_details) lines.push(documentData.vehicle_details);
      if (documentData.vehicle_vin) lines.push(`VIN: ${documentData.vehicle_vin}`);
      if (documentData.vehicle_mileage) lines.push(`Mileage: ${documentData.vehicle_mileage} km`);
      lines.push(``);
    }

    lines.push(`LINE ITEMS`);
    lines.push(`----------`);
    (documentData.line_items || []).forEach(item => {
      lines.push(`${item.description}: ${item.quantity} x ${formatCurrency(item.unit_price || item.rate, currency)} = ${formatCurrency(item.total || item.amount, currency)}`);
    });

    lines.push(``);
    lines.push(`TOTALS`);
    lines.push(`------`);
    lines.push(`Subtotal: ${formatCurrency(documentData.subtotal, currency)}`);
    if (documentData.tax_amount) lines.push(`Tax: ${formatCurrency(documentData.tax_amount, currency)}`);
    lines.push(`Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`);
    if (documentData.amount_paid) lines.push(`Paid: ${formatCurrency(documentData.amount_paid, currency)}`);
    if (documentData.balance_due) lines.push(`Balance Due: ${formatCurrency(documentData.balance_due, currency)}`);

    lines.push(``);
    lines.push(`---`);
    lines.push(`Generated by eFinAuto OFMS • ${new Date().toLocaleString()}`);

    return lines.join('\n');
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(generatePrintHTML());
    printWindow.document.close();
    printWindow.print();
  };

  const generatePrintHTML = () => {
    const lineItemsHTML = (documentData.line_items || []).map(item => `
      <tr>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb;">${item.description}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: center;">${item.quantity}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right;">${formatCurrency(item.unit_price || item.rate, currency)}</td>
        <td style="padding: 8px; border-bottom: 1px solid #e5e7eb; text-align: right; font-weight: 500;">${formatCurrency(item.total || item.amount, currency)}</td>
      </tr>
    `).join('');

    return `
      <html>
        <head>
          <title>${docTitle} - ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: Arial, sans-serif; padding: 20px; max-width: 800px; margin: 0 auto; color: #1f2937; font-size: 11pt; }
            .header { text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 15px; margin-bottom: 20px; }
            .company-name { font-size: 20pt; font-weight: bold; color: #1e293b; }
            .doc-title { font-size: 14pt; color: #6b7280; margin-top: 5px; letter-spacing: 2px; }
            .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-bottom: 20px; }
            .info-box { background: #f9fafb; padding: 12px; border-radius: 6px; }
            .info-box h3 { font-size: 10pt; color: #6b7280; margin-bottom: 5px; text-transform: uppercase; }
            .vehicle-box { background: #eff6ff; padding: 12px; border-radius: 6px; margin-bottom: 20px; border: 1px solid #bfdbfe; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
            th { background: #f3f4f6; padding: 10px; text-align: left; font-size: 10pt; font-weight: 600; }
            td { padding: 8px; font-size: 10pt; }
            .totals { width: 300px; margin-left: auto; }
            .totals tr td { padding: 6px 10px; }
            .totals .total-row { font-size: 14pt; font-weight: bold; background: #eff6ff; }
            .totals .total-row td:last-child { color: #2563eb; }
            .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 9pt; }
            .status-badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 10pt; font-weight: 500; }
            .status-paid { background: #dcfce7; color: #166534; }
            .status-pending { background: #fef3c7; color: #92400e; }
            .status-draft { background: #f3f4f6; color: #374151; }
            .notes { background: #fefce8; padding: 12px; border-radius: 6px; margin-top: 15px; font-size: 10pt; }
            .signature-area { margin-top: 40px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
            .signature-line { border-top: 1px solid #374151; padding-top: 5px; text-align: center; font-size: 10pt; color: #6b7280; }
            @media print { body { padding: 10mm; } .info-box, .vehicle-box { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
          </style>
        </head>
        <body>
          <div class="header">
            <div class="company-name">${company?.name || 'Company Name'}</div>
            <div class="doc-title">${docTitle}</div>
          </div>

          <div class="info-grid">
            <div class="info-box">
              <h3>Bill To</h3>
              <p style="font-weight: 600;">${documentData.customer_name || customer?.full_name || 'Customer'}</p>
              ${documentData.customer_email ? `<p style="font-size: 10pt; color: #6b7280;">${documentData.customer_email}</p>` : ''}
              ${documentData.customer_phone ? `<p style="font-size: 10pt; color: #6b7280;">${documentData.customer_phone}</p>` : ''}
              ${documentData.customer_address ? `<p style="font-size: 10pt; color: #6b7280;">${documentData.customer_address}</p>` : ''}
            </div>
            <div class="info-box" style="text-align: right;">
              <h3>Document Details</h3>
              <p><strong>${docTitle} #:</strong> ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}</p>
              <p><strong>Date:</strong> ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}</p>
              ${documentData.due_date ? `<p><strong>Due:</strong> ${formatDate(documentData.due_date)}</p>` : ''}
              ${documentData.status ? `<p style="margin-top: 8px;"><span class="status-badge status-${documentData.status}">${documentData.status.toUpperCase()}</span></p>` : ''}
            </div>
          </div>

          ${(documentData.vehicle_details || documentData.vehicle_vin) ? `
            <div class="vehicle-box">
              <h3 style="font-size: 10pt; color: #1e40af; margin-bottom: 8px;">VEHICLE INFORMATION</h3>
              ${documentData.vehicle_details ? `<p style="font-weight: 600;">${documentData.vehicle_details}</p>` : ''}
              ${documentData.vehicle_vin ? `<p style="font-size: 10pt;">VIN: ${documentData.vehicle_vin}</p>` : ''}
              ${documentData.vehicle_mileage ? `<p style="font-size: 10pt;">Mileage: ${documentData.vehicle_mileage?.toLocaleString()} km</p>` : ''}
              ${documentData.vehicle_color ? `<p style="font-size: 10pt;">Color: ${documentData.vehicle_color}</p>` : ''}
            </div>
          ` : ''}

          <table>
            <thead>
              <tr>
                <th style="width: 50%;">Description</th>
                <th style="width: 15%; text-align: center;">Qty</th>
                <th style="width: 17%; text-align: right;">Rate</th>
                <th style="width: 18%; text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${lineItemsHTML || '<tr><td colspan="4" style="text-align: center; padding: 20px; color: #9ca3af;">No line items</td></tr>'}
            </tbody>
          </table>

          <table class="totals">
            <tr>
              <td>Subtotal:</td>
              <td style="text-align: right;">${formatCurrency(documentData.subtotal, currency)}</td>
            </tr>
            ${documentData.tax_rate ? `<tr><td>Tax (${documentData.tax_rate}%):</td><td style="text-align: right;">${formatCurrency(documentData.tax_amount, currency)}</td></tr>` : ''}
            ${documentData.discount ? `<tr><td>Discount:</td><td style="text-align: right; color: #dc2626;">-${formatCurrency(documentData.discount, currency)}</td></tr>` : ''}
            <tr class="total-row">
              <td>Total:</td>
              <td style="text-align: right;">${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}</td>
            </tr>
            ${documentData.amount_paid > 0 ? `<tr><td>Amount Paid:</td><td style="text-align: right; color: #16a34a;">${formatCurrency(documentData.amount_paid, currency)}</td></tr>` : ''}
            ${documentData.balance_due > 0 ? `<tr style="font-weight: 600;"><td>Balance Due:</td><td style="text-align: right; color: #dc2626;">${formatCurrency(documentData.balance_due, currency)}</td></tr>` : ''}
          </table>

          ${documentData.notes ? `<div class="notes"><strong>Notes:</strong> ${documentData.notes}</div>` : ''}
          ${documentData.payment_terms ? `<div class="notes" style="background: #f0fdf4;"><strong>Payment Terms:</strong> ${documentData.payment_terms}</div>` : ''}

          ${documentType === 'bill_of_sale' ? `
            <div class="signature-area">
              <div>
                <div class="signature-line">Seller Signature</div>
              </div>
              <div>
                <div class="signature-line">Buyer Signature</div>
              </div>
            </div>
          ` : ''}

          <div class="footer">
            <p>Thank you for your business!</p>
            <p style="margin-top: 5px;">${company?.address || ''} ${company?.city ? `• ${company.city}` : ''} ${company?.province || ''} ${company?.postal_code || ''}</p>
            ${company?.phone ? `<p>Tel: ${company.phone} ${company?.email ? `• ${company.email}` : ''}</p>` : ''}
            ${company?.gst_number ? `<p style="margin-top: 5px;">GST #: ${company.gst_number} ${company?.pst_number ? `• PST #: ${company.pst_number}` : ''}</p>` : ''}
            <p style="margin-top: 10px; font-size: 8pt;">Generated by eFinAuto OFMS • ${new Date().toLocaleString()}</p>
          </div>
        </body>
      </html>
    `;
  };

  const handleDownloadPDF = async () => {
    if (!documentRef.current) return;

    try {
      toast.loading("Generating PDF...");
      const canvas = await html2canvas(documentRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "letter");
      const imgWidth = 216;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      let heightLeft = imgHeight;
      let position = 0;
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= 279;
      
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= 279;
      }
      
      const filename = `${docTitle.replace(/\s/g, '_')}-${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'doc'}.pdf`;
      pdf.save(filename);
      
      toast.dismiss();
      toast.success("PDF downloaded");
      setShareSuccess('pdf');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.dismiss();
      toast.error("Failed to generate PDF");
    }
  };

  const handleEmailShare = async () => {
    const emailTo = documentData.customer_email || customer?.email || prompt("Enter recipient email:");
    if (!emailTo) return;

    setSendingEmail(true);
    try {
      await base44.integrations.Core.SendEmail({
        to: emailTo,
        subject: `${docTitle} ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''} from ${company?.name || 'Our Company'}`,
        body: generatePlainText()
      });
      toast.success(`Sent to ${emailTo}`);
      setShareSuccess('email');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.error("Failed to send email");
    } finally {
      setSendingEmail(false);
    }
  };

  const handleWhatsAppShare = () => {
    const message = `*${docTitle}*
${company?.name || 'Company'}

*#:* ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
*Customer:* ${documentData.customer_name || 'N/A'}
*Date:* ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date)}

*Total:* ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}
${documentData.balance_due > 0 ? `*Balance Due:* ${formatCurrency(documentData.balance_due, currency)}` : ''}

_Generated by eFinAuto OFMS_`;

    const phone = documentData.customer_phone?.replace(/\D/g, '') || '';
    window.open(phone ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : `https://wa.me/?text=${encodeURIComponent(message)}`, "_blank");
    setShareSuccess('whatsapp');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  const handleGoogleChatShare = () => {
    const message = `📄 ${docTitle} #${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
Customer: ${documentData.customer_name || 'N/A'}
Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`;
    navigator.clipboard.writeText(message);
    toast.success("Copied for Google Chat");
    setShareSuccess('gchat');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            {docTitle}
          </DialogTitle>
        </DialogHeader>

        {/* Share Actions */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h3 className="font-semibold flex items-center gap-2 text-sm">
                <Share2 className="w-4 h-4" />
                Print & Share
              </h3>
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="w-4 h-4 mr-2" />
                  Print
                </Button>
                <Button variant="outline" size="sm" onClick={handleDownloadPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  PDF
                  {shareSuccess === 'pdf' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" onClick={handleEmailShare} disabled={sendingEmail}>
                  {sendingEmail ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
                  Email
                  {shareSuccess === 'email' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" className="bg-green-50 text-green-700" onClick={handleWhatsAppShare}>
                  <MessageCircle className="w-4 h-4 mr-2" />
                  WhatsApp
                </Button>
                <Button variant="outline" size="sm" className="bg-blue-50 text-blue-700" onClick={handleGoogleChatShare}>
                  <Copy className="w-4 h-4 mr-2" />
                  Google Chat
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Document Preview */}
        <div ref={documentRef} className="bg-white p-6 border rounded-lg" dangerouslySetInnerHTML={{ __html: generatePrintHTML().replace(/<\/?html>|<\/?head>|<\/?body>|<title>.*?<\/title>|<style>[\s\S]*?<\/style>/gi, '') }} />
      </DialogContent>
    </Dialog>
  );
}