import React, { useRef, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Printer, 
  Download, 
  Mail, 
  MessageCircle, 
  Share2, 
  Copy,
  Loader2,
  CheckCircle,
  FileText
} from "lucide-react";
import { toast } from "sonner";
import { base44 } from "@/api/base44Client";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";

const formatCurrency = (amount, currency = "CAD") => {
  const symbols = { CAD: "CA$", USD: "$", NGN: "₦" };
  return `${symbols[currency] || "$"}${(amount || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  return new Date(dateString).toLocaleDateString('en-CA');
};

const formatPhone = (phone) => {
  if (!phone) return '';
  const cleaned = phone.replace(/\D/g, '');
  if (cleaned.length === 10) {
    return `${cleaned.slice(0, 3)}-${cleaned.slice(3, 6)}-${cleaned.slice(6)}`;
  }
  if (cleaned.length === 11 && cleaned.startsWith('1')) {
    return `${cleaned.slice(1, 4)}-${cleaned.slice(4, 7)}-${cleaned.slice(7)}`;
  }
  return phone;
};

export default function DocumentViewer({ 
  open, 
  onClose, 
  documentType = "invoice", // invoice, quote, bill_of_sale, statement, repair_invoice, freight_invoice
  documentData,
  company,
  customer,
  title
}) {
  const documentRef = useRef(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(null);

  if (!documentData) return null;

  const docTitles = {
    invoice: "INVOICE",
    quote: "QUOTATION",
    bill_of_sale: "BILL OF SALE",
    statement: "ACCOUNT STATEMENT",
    repair_invoice: "REPAIR INVOICE",
    freight_invoice: "FREIGHT INVOICE",
    purchase_order: "PURCHASE ORDER"
  };

  const docTitle = title || docTitles[documentType] || "DOCUMENT";
  const currency = documentData.currency || "CAD";

  const generatePlainText = () => {
    const lines = [
      `${docTitle}`,
      `${company?.name || 'Company'}`,
      `================================`,
      ``,
      `Document #: ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}`,
      `Date: ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}`,
      documentData.due_date ? `Due Date: ${formatDate(documentData.due_date)}` : '',
      ``,
      `Customer: ${documentData.customer_name || customer?.full_name || 'N/A'}`,
      documentData.customer_email ? `Email: ${documentData.customer_email}` : '',
      documentData.customer_phone ? `Phone: ${documentData.customer_phone}` : '',
      documentData.customer_address ? `Address: ${documentData.customer_address}` : '',
      ``
    ].filter(Boolean);

    if (documentData.vehicle_details || documentData.vehicle_vin) {
      lines.push(`VEHICLE INFORMATION`);
      lines.push(`-------------------`);
      if (documentData.vehicle_details) lines.push(documentData.vehicle_details);
      if (documentData.vehicle_vin) lines.push(`VIN: ${documentData.vehicle_vin}`);
      if (documentData.vehicle_mileage) lines.push(`Mileage: ${documentData.vehicle_mileage} km`);
      lines.push(``);
    }

    lines.push(`LINE ITEMS`);
    lines.push(`----------`);
    (documentData.line_items || []).forEach(item => {
      lines.push(`${item.description}: ${item.quantity} x ${formatCurrency(item.unit_price || item.rate, currency)} = ${formatCurrency(item.total || item.amount, currency)}`);
    });

    lines.push(``);
    lines.push(`TOTALS`);
    lines.push(`------`);
    lines.push(`Subtotal: ${formatCurrency(documentData.subtotal, currency)}`);
    if (documentData.tax_amount) lines.push(`Tax: ${formatCurrency(documentData.tax_amount, currency)}`);
    lines.push(`Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`);
    if (documentData.amount_paid) lines.push(`Paid: ${formatCurrency(documentData.amount_paid, currency)}`);
    if (documentData.balance_due) lines.push(`Balance Due: ${formatCurrency(documentData.balance_due, currency)}`);

    lines.push(``);
    lines.push(`---`);
    lines.push(`Generated by eFinAuto OFMS • ${new Date().toLocaleString()}`);

    return lines.join('\n');
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(generatePrintHTML());
    printWindow.document.close();
    printWindow.print();
  };

  const generatePrintHTML = () => {
    const lineItemsHTML = (documentData.line_items || []).map(item => `
      <tr>
        <td style="padding: 10px; border: 1px solid #ddd;">${item.description || ''}</td>
        <td style="padding: 10px; border: 1px solid #ddd; text-align: center;">${item.quantity || 1}</td>
        <td style="padding: 10px; border: 1px solid #ddd; text-align: right;">${formatCurrency(item.unit_price || item.rate || 0, currency)}</td>
        <td style="padding: 10px; border: 1px solid #ddd; text-align: right; font-weight: 500;">${formatCurrency(item.total || item.amount || ((item.quantity || 1) * (item.unit_price || item.rate || 0)), currency)}</td>
      </tr>
    `).join('');

    // Calculate tax properly
    const subtotal = documentData.subtotal || (documentData.line_items || []).reduce((sum, item) => sum + (item.total || item.amount || ((item.quantity || 1) * (item.unit_price || item.rate || 0))), 0);
    const taxRate = documentData.tax_rate || 0;
    const taxAmount = documentData.tax_amount || (subtotal * taxRate / 100);
    const totalAmount = documentData.total_amount || documentData.grand_total || (subtotal + taxAmount);

    return `
      <html>
        <head>
          <title>${docTitle} - ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { font-family: Arial, sans-serif; padding: 30px; max-width: 800px; margin: 0 auto; color: #1f2937; font-size: 11pt; line-height: 1.5; }
            .company-header { margin-bottom: 25px; }
            .company-name { font-size: 22pt; font-weight: bold; color: #1e293b; font-style: italic; margin-bottom: 8px; }
            .company-details { font-size: 10pt; color: #374151; line-height: 1.6; }
            .doc-title { font-size: 18pt; font-weight: bold; color: #1e293b; margin: 25px 0 15px 0; }
            .info-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 30px; margin-bottom: 25px; }
            .bill-to { }
            .bill-to h3 { font-size: 11pt; font-weight: bold; color: #1e293b; margin-bottom: 8px; }
            .bill-to p { font-size: 10pt; color: #374151; margin: 3px 0; }
            .doc-details { text-align: right; }
            .doc-details p { font-size: 10pt; margin: 3px 0; }
            .doc-details strong { color: #6b7280; }
            .vehicle-box { background: #eff6ff; padding: 12px; border-radius: 6px; margin-bottom: 20px; border: 1px solid #bfdbfe; }
            table.items { width: 100%; border-collapse: collapse; margin: 20px 0; }
            table.items th { background: #f3f4f6; padding: 10px; text-align: left; font-size: 10pt; font-weight: 600; border: 1px solid #ddd; }
            table.items th:nth-child(2), table.items th:nth-child(3), table.items th:nth-child(4) { text-align: right; }
            table.items td { padding: 10px; font-size: 10pt; border: 1px solid #ddd; }
            .totals-section { margin-top: 20px; }
            .totals-section p { font-size: 11pt; margin: 5px 0; }
            .totals-section .total-line { font-weight: bold; font-size: 12pt; }
            .thank-you { margin-top: 25px; font-size: 11pt; font-weight: 500; }
            .tax-info { margin-top: 15px; font-size: 10pt; color: #374151; }
            .tax-info p { margin: 3px 0; }
            .footer { margin-top: 30px; padding-top: 15px; border-top: 1px solid #e5e7eb; text-align: center; color: #9ca3af; font-size: 9pt; }
            .notes { background: #fefce8; padding: 12px; border-radius: 6px; margin-top: 15px; font-size: 10pt; }
            .signature-area { margin-top: 40px; display: grid; grid-template-columns: 1fr 1fr; gap: 40px; }
            .signature-line { border-top: 1px solid #374151; padding-top: 5px; text-align: center; font-size: 10pt; color: #6b7280; }
            @media print { body { padding: 15mm; } }
          </style>
        </head>
        <body>
          <div class="company-header">
            <div class="company-name">${company?.name || 'Company Name'}</div>
            <div class="company-details">
              ${company?.address ? `${company.address}<br>` : ''}
              ${company?.city ? `${company.city}, ${company?.province || ''} ${company?.postal_code || ''}<br>` : ''}
              ${company?.phone ? `Tel: ${formatPhone(company.phone)}<br>` : ''}
              ${company?.email ? `${company.email}` : ''}
            </div>
          </div>

          <div class="doc-title">${docTitle}</div>

          <div class="info-grid">
            <div class="bill-to">
              <h3>Bill To:</h3>
              <p style="font-weight: 600;">${documentData.customer_name || customer?.full_name || 'Customer'}</p>
              ${documentData.customer_email ? `<p>${documentData.customer_email}</p>` : ''}
              ${documentData.customer_phone ? `<p>${formatPhone(documentData.customer_phone)}</p>` : ''}
              ${documentData.customer_address ? `<p>${documentData.customer_address}</p>` : ''}
            </div>
            <div class="doc-details">
              <p><strong>${docTitle} #:</strong>${documentData.invoice_number || documentData.quote_number || documentData.sale_number || documentData.order_number || 'N/A'}</p>
              <p><strong>Date:</strong>${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date || documentData.created_date)}</p>
              ${documentData.due_date ? `<p><strong>Due Date:</strong>${formatDate(documentData.due_date)}</p>` : ''}
              ${documentData.currency ? `<p><strong>Currency:</strong>${documentData.currency}</p>` : ''}
              ${documentData.status ? `<p><strong>Status:</strong>${documentData.status}</p>` : ''}
            </div>
          </div>

          ${(documentData.vehicle_details || documentData.vehicle_vin) ? `
            <div class="vehicle-box">
              <h3 style="font-size: 10pt; color: #1e40af; margin-bottom: 8px;">VEHICLE INFORMATION</h3>
              ${documentData.vehicle_details ? `<p style="font-weight: 600;">${documentData.vehicle_details}</p>` : ''}
              ${documentData.vehicle_vin ? `<p style="font-size: 10pt;">VIN: ${documentData.vehicle_vin}</p>` : ''}
              ${documentData.vehicle_mileage ? `<p style="font-size: 10pt;">Mileage: ${documentData.vehicle_mileage?.toLocaleString()} km</p>` : ''}
              ${documentData.vehicle_color ? `<p style="font-size: 10pt;">Color: ${documentData.vehicle_color}</p>` : ''}
            </div>
          ` : ''}

          <table class="items">
            <thead>
              <tr>
                <th style="width: 50%;">Description</th>
                <th style="width: 15%; text-align: center;">Qty</th>
                <th style="width: 17%; text-align: right;">Rate</th>
                <th style="width: 18%; text-align: right;">Amount</th>
              </tr>
            </thead>
            <tbody>
              ${lineItemsHTML || '<tr><td colspan="4" style="text-align: center; padding: 20px; color: #9ca3af;">No line items</td></tr>'}
            </tbody>
          </table>

          <div class="totals-section">
            <p><strong>Subtotal:</strong>${formatCurrency(subtotal, currency)}</p>
            <p><strong>Tax (${taxRate}%):</strong>${formatCurrency(taxAmount, currency)}</p>
            ${documentData.discount ? `<p><strong>Discount:</strong>-${formatCurrency(documentData.discount, currency)}</p>` : ''}
            <p class="total-line"><strong>Total:</strong>${formatCurrency(totalAmount, currency)}</p>
            ${documentData.amount_paid > 0 ? `<p><strong>Amount Paid:</strong>${formatCurrency(documentData.amount_paid, currency)}</p>` : ''}
            ${documentData.balance_due > 0 ? `<p class="total-line"><strong>Balance Due:</strong>${formatCurrency(documentData.balance_due, currency)}</p>` : ''}
          </div>

          <p class="thank-you">Thank you for your business!</p>

          <div class="tax-info">
            ${company?.gst_number ? `<p><strong>GST #:</strong> ${company.gst_number}</p>` : ''}
            ${company?.pst_number ? `<p><strong>PST #:</strong> ${company.pst_number}</p>` : ''}
            ${company?.dealer_permit_number ? `<p><strong>Dealer Permit #:</strong> ${company.dealer_permit_number}</p>` : ''}
          </div>

          ${documentData.notes ? `<div class="notes"><strong>Notes:</strong> ${documentData.notes}</div>` : ''}
          ${documentData.payment_terms ? `<div class="notes" style="background: #f0fdf4;"><strong>Payment Terms:</strong> ${documentData.payment_terms}</div>` : ''}

          ${documentType === 'bill_of_sale' ? `
            <div class="signature-area">
              <div>
                <div class="signature-line">Seller Signature</div>
              </div>
              <div>
                <div class="signature-line">Buyer Signature</div>
              </div>
            </div>
          ` : ''}

          <div class="footer">
            <p style="font-size: 8pt;">Generated by eFinAuto OFMS • ${new Date().toLocaleString()}</p>
          </div>
        </body>
      </html>
    `;
  };

  const handleDownloadPDF = async () => {
    if (!documentRef.current) return;

    try {
      toast.loading("Generating PDF...");
      const canvas = await html2canvas(documentRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "letter");
      const imgWidth = 216;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      let heightLeft = imgHeight;
      let position = 0;
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= 279;
      
      while (heightLeft > 0) {
        position = heightLeft - imgHeight;
        pdf.addPage();
        pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
        heightLeft -= 279;
      }
      
      const filename = `${docTitle.replace(/\s/g, '_')}-${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'doc'}.pdf`;
      pdf.save(filename);
      
      toast.dismiss();
      toast.success("PDF downloaded");
      setShareSuccess('pdf');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.dismiss();
      toast.error("Failed to generate PDF");
    }
  };

  const handleEmailShare = async () => {
    const emailTo = documentData.customer_email || customer?.email || prompt("Enter recipient email:");
    if (!emailTo) return;

    setSendingEmail(true);
    try {
      await base44.integrations.Core.SendEmail({
        to: emailTo,
        subject: `${docTitle} ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || ''} from ${company?.name || 'Our Company'}`,
        body: generatePlainText()
      });
      toast.success(`Sent to ${emailTo}`);
      setShareSuccess('email');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.error("Failed to send email");
    } finally {
      setSendingEmail(false);
    }
  };

  const handleWhatsAppShare = () => {
    const message = `*${docTitle}*
${company?.name || 'Company'}

*#:* ${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
*Customer:* ${documentData.customer_name || 'N/A'}
*Date:* ${formatDate(documentData.invoice_date || documentData.quote_date || documentData.sale_date)}

*Total:* ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}
${documentData.balance_due > 0 ? `*Balance Due:* ${formatCurrency(documentData.balance_due, currency)}` : ''}

_Generated by eFinAuto OFMS_`;

    const phone = documentData.customer_phone?.replace(/\D/g, '') || '';
    window.open(phone ? `https://wa.me/${phone}?text=${encodeURIComponent(message)}` : `https://wa.me/?text=${encodeURIComponent(message)}`, "_blank");
    setShareSuccess('whatsapp');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  const handleGoogleChatShare = () => {
    const message = `📄 ${docTitle} #${documentData.invoice_number || documentData.quote_number || documentData.sale_number || 'N/A'}
Customer: ${documentData.customer_name || 'N/A'}
Total: ${formatCurrency(documentData.total_amount || documentData.grand_total, currency)}`;
    navigator.clipboard.writeText(message);
    toast.success("Copied for Google Chat");
    setShareSuccess('gchat');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-4xl max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="w-5 h-5" />
            {docTitle}
          </DialogTitle>
        </DialogHeader>

        {/* Share Actions */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h3 className="font-semibold flex items-center gap-2 text-sm">
                <Share2 className="w-4 h-4" />
                Print & Share
              </h3>
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="w-4 h-4 mr-2" />
                  Print
                </Button>
                <Button variant="outline" size="sm" onClick={handleDownloadPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  PDF
                  {shareSuccess === 'pdf' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" onClick={handleEmailShare} disabled={sendingEmail}>
                  {sendingEmail ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
                  Email
                  {shareSuccess === 'email' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" className="bg-green-50 text-green-700" onClick={handleWhatsAppShare}>
                  <MessageCircle className="w-4 h-4 mr-2" />
                  WhatsApp
                </Button>
                <Button variant="outline" size="sm" className="bg-blue-50 text-blue-700" onClick={handleGoogleChatShare}>
                  <Copy className="w-4 h-4 mr-2" />
                  Google Chat
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Document Preview */}
        <div ref={documentRef} className="bg-white p-6 border rounded-lg" dangerouslySetInnerHTML={{ __html: generatePrintHTML().replace(/<\/?html>|<\/?head>|<\/?body>|<title>.*?<\/title>|<style>[\s\S]*?<\/style>/gi, '') }} />
      </DialogContent>
    </Dialog>
  );
}