import React, { useRef, useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { 
  Printer, 
  Download, 
  Mail, 
  MessageCircle, 
  Share2, 
  Copy,
  FileText,
  Loader2,
  CheckCircle,
  X
} from "lucide-react";
import { toast } from "sonner";
import { base44 } from "@/api/base44Client";
import html2canvas from "html2canvas";
import jsPDF from "jspdf";
import AIDocumentSummary from "@/components/shared/AIDocumentSummary";

const formatCurrency = (amount) => {
  return (amount || 0).toLocaleString('en-CA', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
};

const formatDate = (dateString) => {
  if (!dateString) return 'N/A';
  const date = new Date(dateString + 'T00:00:00');
  return date.toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: 'numeric' });
};

export default function PaystubViewer({ 
  open, 
  onClose, 
  entry, 
  payrollRun, 
  company, 
  employee,
  allPayrollEntries = [],
  allPayrollRuns = []
}) {
  const paystubRef = useRef(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(null);
  const [generatingPDF, setGeneratingPDF] = useState(false);
  const [pdfUrl, setPdfUrl] = useState(null);

  if (!entry || !payrollRun) return null;

  // Calculate YTD values
  const currentYear = new Date(payrollRun.pay_period_end).getFullYear();
  const previousYTDEntries = allPayrollEntries.filter(e => {
    if (e.id === entry.id || e.employee_id !== entry.employee_id) return false;
    const entryRun = allPayrollRuns.find(r => r.id === e.payroll_run_id);
    if (!entryRun) return false;
    const entryYear = new Date(entryRun.pay_period_end).getFullYear();
    const entryDate = new Date(entryRun.pay_period_end);
    const currentDate = new Date(payrollRun.pay_period_end);
    return entryYear === currentYear && entryDate < currentDate;
  });

  const ytdGross = (entry.ytd_gross > 0) ? entry.ytd_gross : 
    (previousYTDEntries.reduce((sum, e) => sum + (e.gross_pay || 0), 0) + (entry.gross_pay || 0));
  const ytdCPP = (entry.ytd_cpp > 0) ? entry.ytd_cpp :
    (previousYTDEntries.reduce((sum, e) => sum + (e.cpp_employee || 0), 0) + (entry.cpp_employee || 0));
  const ytdEI = (entry.ytd_ei > 0) ? entry.ytd_ei :
    (previousYTDEntries.reduce((sum, e) => sum + (e.ei_employee || 0), 0) + (entry.ei_employee || 0));
  const ytdFederalTax = (entry.ytd_federal_tax > 0) ? entry.ytd_federal_tax :
    (previousYTDEntries.reduce((sum, e) => sum + (e.federal_tax || 0), 0) + (entry.federal_tax || 0));
  const ytdProvincialTax = (entry.ytd_provincial_tax > 0) ? entry.ytd_provincial_tax :
    (previousYTDEntries.reduce((sum, e) => sum + (e.provincial_tax || 0), 0) + (entry.provincial_tax || 0));
  const ytdNet = previousYTDEntries.reduce((sum, e) => sum + (e.net_pay || 0), 0) + (entry.net_pay || 0);

  const generatePlainText = () => {
    return `
PAY STATEMENT
${company?.name || 'Company'}
================================

Employee: ${entry.employee_name}
Employee #: ${entry.employee_number}
Pay Period: ${formatDate(payrollRun.pay_period_start)} - ${formatDate(payrollRun.pay_period_end)}
Pay Date: ${formatDate(payrollRun.pay_date)}

EARNINGS
--------
Regular Hours: ${entry.regular_hours}h @ $${formatCurrency(entry.regular_pay)}
${entry.overtime_hours > 0 ? `Overtime Hours: ${entry.overtime_hours}h @ $${formatCurrency(entry.overtime_pay)}` : ''}
Gross Pay: $${formatCurrency(entry.gross_pay)}

DEDUCTIONS
----------
CPP (Employee): $${formatCurrency(entry.cpp_employee)}
EI (Employee): $${formatCurrency(entry.ei_employee)}
Federal Tax: $${formatCurrency(entry.federal_tax)}
Provincial Tax: $${formatCurrency(entry.provincial_tax)}
Total Deductions: $${formatCurrency(entry.total_deductions)}

NET PAY: $${formatCurrency(entry.net_pay)}
================================

YEAR-TO-DATE SUMMARY
--------------------
YTD Gross: $${formatCurrency(ytdGross)}
YTD CPP: $${formatCurrency(ytdCPP)}
YTD EI: $${formatCurrency(ytdEI)}
YTD Federal Tax: $${formatCurrency(ytdFederalTax)}
YTD Provincial Tax: $${formatCurrency(ytdProvincialTax)}
YTD Net: $${formatCurrency(ytdNet)}

---
Confidential • Generated by eFinAuto OFMS • ${new Date().toLocaleString()}
    `.trim();
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    printWindow.document.write(`
      <html>
        <head>
          <title>Paystub - ${entry.employee_name} - ${formatDate(payrollRun.pay_date)}</title>
          <style>
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body { 
              font-family: Arial, sans-serif; 
              padding: 20px; 
              max-width: 800px; 
              margin: 0 auto;
              color: #1f2937;
              font-size: 11pt;
              line-height: 1.4;
            }
            .header { 
              text-align: center; 
              border-bottom: 2px solid #3b82f6; 
              padding-bottom: 15px; 
              margin-bottom: 20px; 
            }
            .company-name { font-size: 18pt; font-weight: bold; color: #1e293b; }
            .statement-title { font-size: 12pt; color: #6b7280; margin-top: 5px; }
            .info-grid { 
              display: grid; 
              grid-template-columns: 1fr 1fr; 
              gap: 15px; 
              margin-bottom: 20px;
              padding: 10px;
              background: #f9fafb;
              border-radius: 8px;
            }
            .info-grid .left { text-align: left; }
            .info-grid .right { text-align: right; }
            .section { margin-bottom: 15px; }
            .section-title { 
              font-weight: bold; 
              font-size: 11pt;
              border-bottom: 1px solid #e5e7eb; 
              padding-bottom: 5px; 
              margin-bottom: 10px;
              color: #374151;
            }
            .row { 
              display: flex; 
              justify-content: space-between; 
              padding: 4px 0;
              font-size: 10pt;
            }
            .row.total { 
              font-weight: bold; 
              border-top: 1px solid #e5e7eb; 
              padding-top: 8px;
              margin-top: 5px;
            }
            .net-pay-box { 
              background: #eff6ff; 
              padding: 15px; 
              border-radius: 8px; 
              text-align: center;
              margin: 20px 0;
              border: 1px solid #bfdbfe;
            }
            .net-pay-label { font-size: 12pt; font-weight: 600; color: #1e40af; }
            .net-pay-amount { font-size: 24pt; font-weight: bold; color: #2563eb; }
            .ytd-section { 
              background: #f3f4f6; 
              padding: 12px; 
              border-radius: 8px;
              margin-top: 20px;
            }
            .ytd-grid { 
              display: grid; 
              grid-template-columns: repeat(3, 1fr); 
              gap: 10px;
              font-size: 9pt;
            }
            .ytd-item { display: flex; justify-content: space-between; }
            .footer { 
              margin-top: 25px; 
              padding-top: 15px; 
              border-top: 1px solid #e5e7eb; 
              text-align: center; 
              color: #9ca3af; 
              font-size: 8pt; 
            }
            .deduction { color: #dc2626; }
            @media print {
              body { padding: 15mm; }
              .net-pay-box { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
              .ytd-section { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
              .info-grid { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            }
          </style>
        </head>
        <body>
          <div class="header">
            ${company?.logo_url 
              ? `<img src="${company.logo_url}" alt="${company?.name}" style="max-height:50px;max-width:150px;object-fit:contain;margin-bottom:8px;" onerror="this.style.display='none'"/>`
              : ''}
            <div class="company-name">${company?.name || 'Company Name'}</div>
            <div class="statement-title">Pay Statement</div>
          </div>

          <div class="info-grid">
            <div class="left">
              <div><strong>${entry.employee_name}</strong></div>
              <div style="color: #6b7280; font-size: 10pt;">Employee #: ${entry.employee_number}</div>
            </div>
            <div class="right">
              <div style="font-size: 10pt;">Pay Period: ${formatDate(payrollRun.pay_period_start)} - ${formatDate(payrollRun.pay_period_end)}</div>
              <div style="font-size: 10pt;">Pay Date: ${formatDate(payrollRun.pay_date)}</div>
            </div>
          </div>

          <div class="section">
            <div class="section-title">EARNINGS</div>
            <div class="row">
              <span>Regular Hours (${entry.regular_hours}h)</span>
              <span>$${formatCurrency(entry.regular_pay)}</span>
            </div>
            ${entry.overtime_hours > 0 ? `
            <div class="row">
              <span>Overtime Hours (${entry.overtime_hours}h)</span>
              <span>$${formatCurrency(entry.overtime_pay)}</span>
            </div>
            ` : ''}
            ${entry.vacation_accrued > 0 ? `
            <div class="row">
              <span>Vacation Accrued</span>
              <span>$${formatCurrency(entry.vacation_accrued)}</span>
            </div>
            ` : ''}
            <div class="row total">
              <span>Gross Pay</span>
              <span>$${formatCurrency(entry.gross_pay)}</span>
            </div>
          </div>

          <div class="section">
            <div class="section-title">DEDUCTIONS</div>
            <div class="row">
              <span>CPP (Employee)</span>
              <span class="deduction">(${formatCurrency(entry.cpp_employee)})</span>
            </div>
            <div class="row">
              <span>EI (Employee)</span>
              <span class="deduction">(${formatCurrency(entry.ei_employee)})</span>
            </div>
            <div class="row">
              <span>Federal Income Tax</span>
              <span class="deduction">(${formatCurrency(entry.federal_tax)})</span>
            </div>
            <div class="row">
              <span>Provincial Income Tax</span>
              <span class="deduction">(${formatCurrency(entry.provincial_tax)})</span>
            </div>
            <div class="row total">
              <span>Total Deductions</span>
              <span class="deduction">(${formatCurrency(entry.total_deductions)})</span>
            </div>
          </div>

          <div class="net-pay-box">
            <div class="net-pay-label">NET PAY</div>
            <div class="net-pay-amount">$${formatCurrency(entry.net_pay)}</div>
          </div>

          <div class="ytd-section">
            <div class="section-title" style="margin-bottom: 8px;">YEAR-TO-DATE SUMMARY</div>
            <div class="ytd-grid">
              <div class="ytd-item"><span>YTD Gross:</span><span>$${formatCurrency(ytdGross)}</span></div>
              <div class="ytd-item"><span>YTD CPP:</span><span>$${formatCurrency(ytdCPP)}</span></div>
              <div class="ytd-item"><span>YTD EI:</span><span>$${formatCurrency(ytdEI)}</span></div>
              <div class="ytd-item"><span>YTD Fed Tax:</span><span>$${formatCurrency(ytdFederalTax)}</span></div>
              <div class="ytd-item"><span>YTD Prov Tax:</span><span>$${formatCurrency(ytdProvincialTax)}</span></div>
              <div class="ytd-item"><span>YTD Net:</span><span>$${formatCurrency(ytdNet)}</span></div>
            </div>
          </div>

          <div class="section" style="margin-top: 15px;">
            <div class="section-title">EMPLOYER CONTRIBUTIONS</div>
            <div class="row">
              <span>CPP (Employer)</span>
              <span>$${formatCurrency(entry.cpp_employer)}</span>
            </div>
            <div class="row">
              <span>EI (Employer)</span>
              <span>$${formatCurrency(entry.ei_employer)}</span>
            </div>
          </div>

          <div class="footer">
            <p>Confidential • This is an official pay statement</p>
            <p>Generated by eFinAuto OFMS • ${new Date().toLocaleString()}</p>
            ${company?.gst_number ? `<p>GST #: ${company.gst_number}</p>` : ''}
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleDownloadPDF = async () => {
    if (!paystubRef.current) return;

    try {
      toast.loading("Generating PDF...");
      const canvas = await html2canvas(paystubRef.current, { 
        scale: 2, 
        useCORS: true,
        backgroundColor: '#ffffff'
      });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "letter");
      const imgWidth = 216;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
      pdf.save(`Paystub-${entry.employee_name.replace(/\s/g, '_')}-${payrollRun.pay_date}.pdf`);
      
      toast.dismiss();
      toast.success("PDF downloaded successfully");
      setShareSuccess('pdf');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.dismiss();
      toast.error("Failed to generate PDF");
    }
  };

  const handleEmailShare = async () => {
    const emailTo = employee?.email || prompt("Enter recipient email address:");
    if (!emailTo) return;

    setSendingEmail(true);
    try {
      const emailBody = `
Dear ${entry.employee_name},

Please find your pay statement details below for the pay period ${formatDate(payrollRun.pay_period_start)} - ${formatDate(payrollRun.pay_period_end)}.

${generatePlainText()}

If you have any questions about your pay statement, please contact HR.

Best regards,
${company?.name || 'Payroll Department'}
${company?.email || ''}
${company?.phone || ''}
      `.trim();

      await base44.integrations.Core.SendEmail({
        to: emailTo,
        subject: `Pay Statement - ${formatDate(payrollRun.pay_period_start)} to ${formatDate(payrollRun.pay_period_end)}`,
        body: emailBody
      });

      toast.success(`Paystub sent to ${emailTo}`);
      setShareSuccess('email');
      setTimeout(() => setShareSuccess(null), 3000);
    } catch (error) {
      toast.error("Failed to send email");
    } finally {
      setSendingEmail(false);
    }
  };

  const generateAndUploadPDF = async () => {
    if (!paystubRef.current) return null;
    
    setGeneratingPDF(true);
    try {
      const canvas = await html2canvas(paystubRef.current, { scale: 2, useCORS: true, backgroundColor: '#ffffff' });
      const imgData = canvas.toDataURL("image/png");
      const pdf = new jsPDF("p", "mm", "letter");
      const imgWidth = 216;
      const imgHeight = (canvas.height * imgWidth) / canvas.width;
      
      pdf.addImage(imgData, "PNG", 0, 0, imgWidth, imgHeight);
      
      // Convert PDF to blob and upload to cloud
      const pdfBlob = pdf.output('blob');
      const filename = `Paystub-${entry.employee_name.replace(/\s/g, '_')}-${payrollRun.pay_date}.pdf`;
      const file = new File([pdfBlob], filename, { type: 'application/pdf' });
      
      const { file_url } = await base44.integrations.Core.UploadFile({ file });
      setPdfUrl(file_url);
      setGeneratingPDF(false);
      return file_url;
    } catch (error) {
      console.error("PDF generation error:", error);
      setGeneratingPDF(false);
      toast.error("Failed to generate PDF");
      return null;
    }
  };

  const handleWhatsAppShare = async () => {
    let url = pdfUrl;
    
    // Generate and upload PDF if not already done
    if (!url) {
      toast.loading("Generating PDF for sharing...");
      url = await generateAndUploadPDF();
      toast.dismiss();
      if (!url) return;
    }

    const message = `
*📄 PAY STATEMENT*
${company?.name || 'Company'}

*Employee:* ${entry.employee_name}
*Pay Period:* ${formatDate(payrollRun.pay_period_start)} - ${formatDate(payrollRun.pay_period_end)}
*Pay Date:* ${formatDate(payrollRun.pay_date)}

*Earnings*
Gross Pay: $${formatCurrency(entry.gross_pay)}

*Deductions*
CPP: $${formatCurrency(entry.cpp_employee)}
EI: $${formatCurrency(entry.ei_employee)}
Federal Tax: $${formatCurrency(entry.federal_tax)}
Provincial Tax: $${formatCurrency(entry.provincial_tax)}
Total: $${formatCurrency(entry.total_deductions)}

*💰 NET PAY: $${formatCurrency(entry.net_pay)}*

📄 *Download PDF:* ${url}

_Confidential - Generated by eFinAuto OFMS_
    `.trim();

    const phoneNumber = employee?.phone?.replace(/\D/g, '') || '';
    const whatsappUrl = phoneNumber 
      ? `https://wa.me/${phoneNumber}?text=${encodeURIComponent(message)}`
      : `https://wa.me/?text=${encodeURIComponent(message)}`;
    
    window.open(whatsappUrl, "_blank");
    setShareSuccess('whatsapp');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  const handleGoogleChatShare = async () => {
    let url = pdfUrl;
    
    // Generate and upload PDF if not already done
    if (!url) {
      toast.loading("Generating PDF for sharing...");
      url = await generateAndUploadPDF();
      toast.dismiss();
      if (!url) return;
    }

    const message = `📄 Pay Statement - ${entry.employee_name}
Pay Period: ${formatDate(payrollRun.pay_period_start)} - ${formatDate(payrollRun.pay_period_end)}
Gross: $${formatCurrency(entry.gross_pay)} | Deductions: $${formatCurrency(entry.total_deductions)} | Net: $${formatCurrency(entry.net_pay)}
Download PDF: ${url}`;
    
    navigator.clipboard.writeText(message);
    toast.success("Copied to clipboard with PDF link - Paste in Google Chat");
    setShareSuccess('gchat');
    setTimeout(() => setShareSuccess(null), 3000);
  };

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-3xl max-h-[95vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex justify-between items-center">
            <DialogTitle className="flex items-center gap-2">
              <FileText className="w-5 h-5" />
              Pay Statement
            </DialogTitle>
          </div>
        </DialogHeader>

        {/* Share Actions Bar */}
        <Card className="mb-4">
          <CardContent className="p-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <h3 className="font-semibold flex items-center gap-2 text-sm">
                <Share2 className="w-4 h-4" />
                Print & Share
              </h3>
              <div className="flex flex-wrap gap-2">
                <Button variant="outline" size="sm" onClick={handlePrint}>
                  <Printer className="w-4 h-4 mr-2" />
                  Print
                  {shareSuccess === 'print' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" onClick={handleDownloadPDF}>
                  <Download className="w-4 h-4 mr-2" />
                  PDF
                  {shareSuccess === 'pdf' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" onClick={handleEmailShare} disabled={sendingEmail}>
                  {sendingEmail ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Mail className="w-4 h-4 mr-2" />}
                  Email
                  {shareSuccess === 'email' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" className="bg-green-50 text-green-700 hover:bg-green-100" onClick={handleWhatsAppShare} disabled={generatingPDF}>
                  {generatingPDF ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <MessageCircle className="w-4 h-4 mr-2" />}
                  WhatsApp
                  {shareSuccess === 'whatsapp' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
                <Button variant="outline" size="sm" className="bg-blue-50 text-blue-700 hover:bg-blue-100" onClick={handleGoogleChatShare} disabled={generatingPDF}>
                  {generatingPDF ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Copy className="w-4 h-4 mr-2" />}
                  Google Chat
                  {shareSuccess === 'gchat' && <CheckCircle className="w-4 h-4 ml-1 text-green-600" />}
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Paystub Content */}
        <div ref={paystubRef} className="bg-white p-6 border rounded-lg">
          {/* Header */}
          <div className="text-center border-b-2 border-blue-600 pb-4 mb-6">
            {company?.logo_url && (
              <img 
                src={company.logo_url} 
                alt={company?.name} 
                className="max-h-12 max-w-[150px] object-contain mx-auto mb-2"
                onError={(e) => { e.target.style.display = 'none'; }}
              />
            )}
            <h1 className="text-2xl font-bold text-slate-800">{company?.name || 'Company Name'}</h1>
            <p className="text-gray-500">Pay Statement</p>
          </div>

          {/* Employee & Period Info */}
          <div className="grid grid-cols-2 gap-4 mb-6 bg-gray-50 p-4 rounded-lg">
            <div>
              <p className="font-bold text-lg">{entry.employee_name}</p>
              <p className="text-gray-600 text-sm">Employee #: {entry.employee_number}</p>
            </div>
            <div className="text-right text-sm">
              <p>Pay Period: {formatDate(payrollRun.pay_period_start)} - {formatDate(payrollRun.pay_period_end)}</p>
              <p>Pay Date: {formatDate(payrollRun.pay_date)}</p>
            </div>
          </div>

          {/* Earnings Section */}
          <div className="mb-6">
            <h3 className="font-bold text-sm border-b pb-2 mb-3 text-gray-700">EARNINGS</h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span>Regular Hours ({entry.regular_hours}h)</span>
                <span>${formatCurrency(entry.regular_pay)}</span>
              </div>
              {entry.overtime_hours > 0 && (
                <div className="flex justify-between">
                  <span>Overtime Hours ({entry.overtime_hours}h)</span>
                  <span>${formatCurrency(entry.overtime_pay)}</span>
                </div>
              )}
              {entry.vacation_accrued > 0 && (
                <div className="flex justify-between text-gray-600">
                  <span>Vacation Accrued</span>
                  <span>${formatCurrency(entry.vacation_accrued)}</span>
                </div>
              )}
              <div className="flex justify-between font-bold pt-2 border-t">
                <span>Gross Pay</span>
                <span>${formatCurrency(entry.gross_pay)}</span>
              </div>
            </div>
          </div>

          {/* Deductions Section */}
          <div className="mb-6">
            <h3 className="font-bold text-sm border-b pb-2 mb-3 text-gray-700">DEDUCTIONS</h3>
            <div className="space-y-2 text-sm">
              <div className="flex justify-between">
                <span>CPP (Employee)</span>
                <span className="text-red-600">(${formatCurrency(entry.cpp_employee)})</span>
              </div>
              <div className="flex justify-between">
                <span>EI (Employee)</span>
                <span className="text-red-600">(${formatCurrency(entry.ei_employee)})</span>
              </div>
              <div className="flex justify-between">
                <span>Federal Income Tax</span>
                <span className="text-red-600">(${formatCurrency(entry.federal_tax)})</span>
              </div>
              <div className="flex justify-between">
                <span>Provincial Income Tax</span>
                <span className="text-red-600">(${formatCurrency(entry.provincial_tax)})</span>
              </div>
              <div className="flex justify-between font-bold pt-2 border-t">
                <span>Total Deductions</span>
                <span className="text-red-600">(${formatCurrency(entry.total_deductions)})</span>
              </div>
            </div>
          </div>

          {/* Net Pay Box */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 text-center mb-6">
            <p className="text-sm font-semibold text-blue-800">NET PAY</p>
            <p className="text-3xl font-bold text-blue-600">${formatCurrency(entry.net_pay)}</p>
          </div>

          {/* YTD Summary */}
          <div className="bg-gray-50 rounded-lg p-4 mb-6">
            <h3 className="font-bold text-sm border-b pb-2 mb-3 text-gray-700">YEAR-TO-DATE SUMMARY</h3>
            <div className="grid grid-cols-3 gap-x-4 gap-y-2 text-xs">
              <div className="flex justify-between">
                <span>YTD Gross:</span>
                <span className="font-semibold">${formatCurrency(ytdGross)}</span>
              </div>
              <div className="flex justify-between">
                <span>YTD CPP:</span>
                <span className="font-semibold">${formatCurrency(ytdCPP)}</span>
              </div>
              <div className="flex justify-between">
                <span>YTD EI:</span>
                <span className="font-semibold">${formatCurrency(ytdEI)}</span>
              </div>
              <div className="flex justify-between">
                <span>YTD Fed Tax:</span>
                <span className="font-semibold">${formatCurrency(ytdFederalTax)}</span>
              </div>
              <div className="flex justify-between">
                <span>YTD Prov Tax:</span>
                <span className="font-semibold">${formatCurrency(ytdProvincialTax)}</span>
              </div>
              <div className="flex justify-between">
                <span>YTD Net:</span>
                <span className="font-semibold">${formatCurrency(ytdNet)}</span>
              </div>
            </div>
          </div>

          {/* Employer Contributions */}
          <div className="mb-6">
            <h3 className="font-bold text-sm border-b pb-2 mb-3 text-gray-700">EMPLOYER CONTRIBUTIONS</h3>
            <div className="space-y-2 text-sm text-gray-600">
              <div className="flex justify-between">
                <span>CPP (Employer Portion)</span>
                <span>${formatCurrency(entry.cpp_employer)}</span>
              </div>
              <div className="flex justify-between">
                <span>EI (Employer Portion)</span>
                <span>${formatCurrency(entry.ei_employer)}</span>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center pt-4 border-t text-xs text-gray-400">
            <p>Confidential • This is an official pay statement</p>
            <p>Generated by eFinAuto OFMS • {new Date().toLocaleString()}</p>
            {company?.gst_number && <p>GST #: {company.gst_number}</p>}
          </div>
        </div>

        {/* AI Summary */}
        <AIDocumentSummary
          documentType="paystub"
          documentData={{
            ...entry,
            pay_period_start: payrollRun?.pay_period_start,
            pay_period_end: payrollRun?.pay_period_end,
            pay_date: payrollRun?.pay_date,
            ytd_gross: ytdGross
          }}
          company={company}
        />

        {/* Share Success Summary */}
        {shareSuccess && (
          <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded-lg flex items-center gap-2 text-green-800">
            <CheckCircle className="w-5 h-5" />
            <span className="text-sm font-medium">
              {shareSuccess === 'pdf' && 'PDF downloaded successfully'}
              {shareSuccess === 'email' && 'Email sent successfully'}
              {shareSuccess === 'whatsapp' && 'WhatsApp opened - paste to send'}
              {shareSuccess === 'gchat' && 'Copied to clipboard for Google Chat'}
              {shareSuccess === 'print' && 'Print dialog opened'}
            </span>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}